### ISSUE TITLE
How to run the model on CPU or a sigle GPU? 

### ISSUE THREAD

**Issue by N-Jaro** [kaushik333/Piggyback-GAN-Pytorch#2]
Hi team,

Thank you very much for your great work. This is very interesting work for Transfer learning. 

I want to replicate your work on my own environment. However, I only have a CPU or a single GPU that I can use. When I try to run the script (python pb_cycleGAN.py train=True) it always shows an error as follows: 

```
Traceback (most recent call last):
  File "pb_cycleGAN.py", line 263, in <module>
    main()
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "pb_cycleGAN.py", line 227, in main
    train(-1, opt)
  File "pb_cycleGAN.py", line 54, in train
    print("Length of loader is ",len(train_loader))
UnboundLocalError: local variable 'train_loader' referenced before assignment
```

I did some investigation and found that CycleGAN can be run in CPU mode with gpu_ids=-1, which is the default value of the input parameter. And when I tried changing the gpu_ids to = -1 in cycle_GAN_config.py, the error seems to be thrown by the pytorch multiprocessing process, specifically mp.spawn() function. 

Changes in cycle_GAN_config.py

from  self.gpu_ids = [0,1,2,3] to self.gpu_ids = [-1]

Error message: 
```
Traceback (most recent call last):
  File "pb_cycleGAN.py", line 263, in <module>
    main()
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "pb_cycleGAN.py", line 228, in main
    mp.spawn(train, nprocs=len(opt.gpu_ids), args=(opt,))
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/keeling/a/nj7/Piggyback-GAN-Pytorch/pb_cycleGAN.py", line 26, in train
    torch.cuda.set_device(gpu)
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/torch/cuda/__init__.py", line 292, in set_device
    torch._C._cuda_setDevice(device)
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/torch/cuda/__init__.py", line 196, in _lazy_init
    _check_driver()
  File "/data/keeling/a/nj7/anaconda2/envs/PiggybackGAN/lib/python3.6/site-packages/torch/cuda/__init__.py", line 101, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

Please advise. 
Nattapon J.

**Comment by kaushik333** [comment]
I am terribly sorry for the slow response as Ive been busy. 

I havent had the chance to look into this in detail. It looks like my code only works in the multi-GPU mode. I think the reason is because I'm using DistributedDataParallel which is meant to run models on parallel GPUs. But I should perhaps include an if-else case to not use nn.DDP in cpu mode. 

It would be something like 
if len(gpu) == 0:
     # run in CPU mode
else:
    # run in DDP mode

Also a simpler alternative is to just to do model = model.to(device) and provide only one GPU which should work. You can remove mp.spawn() as that is used to spawn one process per GPU (which should technically work even for one GPU, but I dont know why it doesnt -- will look into it). 

Please look at how nn.DDP() is used and you can take the core of it from the train function and just run it on one device.

This is just a quick suggestion as I have not had the time to run the code again on my end to fix bugs. 

I will try to work on this sometime and push an update. But meanwhile, I hope the above is of some little help.
